apiVersion: v1
kind: Service
metadata:
  labels:
    app: "nginx-backend"
  name: "nginx-backend"
  namespace: "default"
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: "nginx-backend"
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-backend
  name: nginx-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "nginx-backend"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "nginx-backend"
    spec:
      volumes:
      - name: nginx-certs
        configMap:
          name: nginx-certs
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-html
        configMap:
          name: nginx-html
      containers:
      - name: "nginx-backend"
        image: harbor.run.haas-242.pez.pivotal.io/library/nginx:signed
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/nginx/certs
          name: nginx-certs
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
        - mountPath: /etc/nginx/html
          name: nginx-html
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP