apiVersion: v1
data:
  nginx.conf: |-
    server {
        listen 80;
        listen 443 ssl;
        ssl_certificate /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;
    }
kind: ConfigMap
metadata:
  name: nginx-config