apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: nginx-backend
spec:
  virtualhost:
    fqdn: myapp.mydomain.com
    tls:
      secretName: nginx-backend-ingress-cert
      clientValidation:
        caSecret: client-ca-crt  
  routes:
    - conditions:
      - prefix: /
      services:
        - name: nginx-backend
          port: 443
          protocol: tls
      loadBalancerPolicy:
        strategy: Cookie